FROM ubuntu:20.04
LABEL foo.oak.docker.image.authors="alex carvalho" \
      foo.oak.docker.image.name="oak/pyspark" \
      foo.oak.docker.image.version="0.2.2" \
      foo.oak.docker.image.description="Image to mimic Databricks runtime 11.3 LTS"


ENTRYPOINT ["top", "-b"]